# Generated by Django 5.0.1 on 2024-11-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outflow",
            name="outflow_cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="outflow",
            name="outflow_selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
