# Generated by Django 5.1.6 on 2025-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_remove_outflow_quantity_outflow_quantity_size_g_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saídas'},
        ),
        migrations.AddField(
            model_name='outflow',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Cliente'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone do Cliente'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='payment_type',
            field=models.CharField(choices=[('À VISTA', 'À VISTA'), ('A PRAZO', 'A PRAZO'), ('A RECEBER À VISTA', 'A RECEBER À VISTA')], max_length=100, verbose_name='Pagamento'),
        ),
    ]
