# Generated by Django 5.1.6 on 2025-03-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_remove_inflow_quantity_inflow_quantity_size_g_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entradas'},
        ),
    ]
