# Generated by Django 5.0.1 on 2024-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cash_selling_price",
            field=models.DecimalField(
                decimal_places=2, default="À VISTA", max_digits=20
            ),
            preserve_default=False,
        ),
    ]
