# Generated by Django 5.0.1 on 2024-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_cash_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cash_selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
