# Generated by Django 5.1.6 on 2025-03-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Produtos'},
        ),
    ]
